version: '3.8'

services:
  # --- CEREBRO (Backend) ---
  api:
    build: ./backend
    container_name: repara_xpress_api
    restart: always
    # Ya no exponemos el puerto 8000 al mundo, solo a la red interna (seguridad)
    expose:
      - "8000"
    volumes:
      - ./backend:/code
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - TZ=${TZ}
      - CORS_ORIGINS=${CORS_ORIGINS}
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "python -m alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

  # --- CARA (Frontend) ---
  frontend:
    build: ./frontend
    container_name: repara_xpress_frontend
    restart: always
    # Ya no exponemos el 5173 al mundo, solo a la red interna
    expose:
      - "5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      # Forzamos la dirección correcta directamente aquí para evitar errores de lectura
      - VITE_API_URL=/api
    depends_on:
      - api

  # --- RECEPCIONISTA (Nginx) ---
  nginx:
    image: nginx:latest
    container_name: repara_xpress_nginx
    restart: always
    ports:
      # Esta es la ÚNICA puerta abierta al mundo (Puerto estándar web)
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
      - frontend

  # --- EL TÚNEL (Cloudflare) ---
  tunnel:
    image: cloudflare/cloudflared:latest
    restart: always
    command: tunnel --url http://nginx:80
    # Esto le dice: "Cava un túnel público que lleve a la puerta del recepcionista (nginx)"

  # --- MEMORIA (Base de Datos) ---
  db:
    image: postgres:15
    container_name: repara_xpress_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backups:/backups
    env_file:
      - .env
    environment:
      - POSTGRES_USER=repara_user
      - POSTGRES_PASSWORD=repara_password
      - POSTGRES_DB=repara_xpress_inventory_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U repara_user -d repara_xpress_inventory_db"]
      interval: 5s
      timeout: 5s
      retries: 5



volumes:
  postgres_data: